### ISSUE TITLE
有个疑问，这里为什么不进行签名呢？

### ISSUE THREAD

**Issue by sullay** [eggjs/security#87]
![image](https://github.com/eggjs/egg-security/assets/30190109/ac40802a-39ac-414a-9788-ab94974591db)
![image](https://github.com/eggjs/egg-security/assets/30190109/05e0d3a4-44f7-4d21-9402-b2172e2eb628)

如果进行签名是不是可以防止子域存在存在xss漏洞修改了csrfToken的情况

**Comment by fengmk2** [comment]
忘记了当时为啥没加。看到 pr 了，我会尽快 review。
