### ISSUE TITLE
不安全地址补充

### ISSUE THREAD

**Issue by TangTang25** [eggjs/security#91]
类似https://test.github.com\\@baidu.com这样的地址是不安全的，在domainWhiteList里添加了test.github.com之后还是会redirect，实际上跳转到了baidu.com，希望加上对pathname的过滤

**Comment by fengmk2** [comment]
可以来提交一个 pr 修复？

**Comment by fengmk2** [comment]
`https://github.com\\@baidu.com`  并不会跳转到 baidu.com ?
你说的这个问题是怎样重现的？

**Comment by fengmk2** [comment]
复现了。

**Comment by fengmk2** [comment]
将 `http://github.com\@baidu.com` 通过 `ctx.redirect('http://github.com\\@baidu.com')` 之后会响应经过转码之后的 location，从而导致浏览器跳转到了 baidu.com

```bash
< location: http://github.com%5C@baidu.com
```

**Comment by fengmk2** [comment]
https://github.com/koajs/koa/pull/1803
