### ISSUE TITLE
我现在项目使用漏洞检查OpenSCA扫描出来egg-security下面的“ip”依赖包有漏洞需要需升高版本“Remediation Upgrade `ip` to version 1.1.9, 2.0.1 or higher.”

### ISSUE THREAD

**Issue by LinhoonYu** [eggjs/security#92]
![6736cb38e85c71bb032eead35499101](https://github.com/eggjs/egg-security/assets/167730099/33b5f51f-efd6-44d1-b8a4-416ceebc1b96)

**Comment by fengmk2** [comment]
是不是你锁了版本？https://github.com/eggjs/egg-security/blob/master/package.json#L23 重新安装依赖就会自动更新到 ip 库的最新版本

**Comment by LinhoonYu** [comment]
谢谢大佬，我再试试
